
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ include "dubbizle.fullname" . }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: {{ include "dubbizle.fullname" . }}
 minReplicas: 1
 maxReplicas: 2
 targetCPUUtilizationPercentage: 85
