apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment

  labels:

    name: nginx-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      name: nginx

  template:

    metadata:

      labels:

        name: nginx

    spec:

      volumes:

      - name: shared-logs 

        emptyDir: {}

      - name: config-map

        configMap:

          name: config-map


      containers:

      - name: webapp

        image: alpine # alpine is a simple Linux OS image

        command: ["/bin/sh"]

        args: ["-ec", "echo 'Itsworking' >> /var/log/check.txt ; sleep 1;  echo 'NOTFOUND' >> /var/log/402 ; sleep 2 ; echo 'FORBIDDEN' >> /var/log/403 ; sleep 3; echo 'ApplicationError' >> /var/log/502 ; sleep 3;  echo 'BADGATEWAY' >> /var/log/503; sleep 3; exit 0;"]

        volumeMounts:

        - name: shared-logs

          mountPath: /var/log

      - name: nginx

        image: nginx:alpine

        ports:

        - containerPort: 80

        volumeMounts:

        - name: shared-logs

          mountPath: /usr/share/nginx/html

        - name: config-map

          mountPath: /etc/nginx/conf.d/default.conf

          subPath: default.conf
